"""Référence descriptive du schéma SQL de l'application."""

TABLES = {
    "config": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom_asso TEXT NOT NULL DEFAULT 'Mon Association'",
        "exercice TEXT",
        "date_debut TEXT",
        "date_fin TEXT",
        "solde_ouverture REAL DEFAULT 0",
        "disponible_banque REAL DEFAULT 0",
        "cloture INTEGER DEFAULT 0",
        "solde_report REAL DEFAULT 0",
    ),
    "membres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "prenom TEXT NOT NULL",
        "email TEXT",
        "telephone TEXT",
        "cotisation TEXT",
        "statut TEXT DEFAULT 'actif'",
        "date_adhesion TEXT",
        "commentaire TEXT",
        "statut_archive INTEGER DEFAULT 0",
    ),
    "categories": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL UNIQUE",
        "parent_id INTEGER REFERENCES categories(id)",
    ),
    "evenements": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "date TEXT",
        "lieu TEXT",
        "description TEXT",
    ),
    "stock": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie_id INTEGER REFERENCES categories(id)",
        "quantite INTEGER DEFAULT 0",
        "seuil_alerte INTEGER DEFAULT 0",
        "date_peremption TEXT",
        "lot TEXT",
        "commentaire TEXT",
    ),
    "mouvements_stock": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "stock_id INTEGER NOT NULL REFERENCES stock(id)",
        "date TEXT NOT NULL",
        "type TEXT NOT NULL",
        "quantite INTEGER NOT NULL",
        "prix_unitaire REAL",
        "commentaire TEXT",
    ),
    "dons_subventions": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "source TEXT",
        "montant REAL NOT NULL",
        "type TEXT",
        "justificatif TEXT",
        "commentaire TEXT",
        "membre_id INTEGER REFERENCES membres(id)",
    ),
    "depenses_regulieres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_depense TEXT NOT NULL",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
        "membre_id INTEGER REFERENCES membres(id)",
        "statut_remboursement TEXT DEFAULT 'non concerné'",
    ),
    "depenses_diverses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_depense TEXT NOT NULL",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
        "membre_id INTEGER REFERENCES membres(id)",
        "statut_remboursement TEXT DEFAULT 'non concerné'",
    ),
    "depots_retraits_banque": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "type TEXT NOT NULL",
        "montant REAL NOT NULL",
        "reference TEXT",
        "banque TEXT",
        "pointe INTEGER DEFAULT 0",
        "commentaire TEXT",
    ),
    "fournisseurs": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL UNIQUE",
    ),
    "historique_clotures": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_cloture TEXT NOT NULL",
        "exercice TEXT",
        "solde_final REAL",
    ),
    "buvette_articles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie TEXT",
        "unite TEXT",
        "contenance TEXT",
        "prix_vente REAL DEFAULT 0",
        "prix_achat REAL DEFAULT 0",
        "stock INTEGER DEFAULT 0",
        "commentaire TEXT",
    ),
    "buvette_achats": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "article_id INTEGER NOT NULL REFERENCES buvette_articles(id)",
        "date_achat TEXT NOT NULL",
        "quantite INTEGER NOT NULL",
        "prix_unitaire REAL",
        "fournisseur TEXT",
        "numero_facture TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaires": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_inventaire TEXT NOT NULL",
        "evenement_id INTEGER REFERENCES evenements(id)",
        "type_inventaire TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaire_lignes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "inventaire_id INTEGER NOT NULL REFERENCES buvette_inventaires(id)",
        "article_id INTEGER NOT NULL REFERENCES buvette_articles(id)",
        "quantite INTEGER NOT NULL",
        "commentaire TEXT",
    ),
    "buvette_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER REFERENCES evenements(id)",
        "date_recette TEXT NOT NULL",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_modules": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_module TEXT NOT NULL",
    ),
    "evenement_module_champs": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER NOT NULL REFERENCES evenement_modules(id)",
        "nom_champ TEXT NOT NULL",
        "type_champ TEXT NOT NULL",
        "prix_unitaire REAL",
    ),
    "evenement_module_data": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER NOT NULL REFERENCES evenement_modules(id)",
        "ligne_index INTEGER NOT NULL",
        "champ_id INTEGER NOT NULL REFERENCES evenement_module_champs(id)",
        "valeur TEXT",
    ),
    "evenement_paiements": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_payeur TEXT",
        "classe TEXT",
        "mode_paiement TEXT",
        "banque TEXT",
        "numero_cheque TEXT",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_caisses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_caisse TEXT NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "source TEXT",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_depenses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "date_depense TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
    ),
    "retrocessions_ecoles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "ecole TEXT NOT NULL",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "remboursements": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "depense_type TEXT NOT NULL CHECK(depense_type IN ('reguliere', 'diverse', 'evenement'))",
        "depense_id INTEGER NOT NULL",
        "membre_id INTEGER NOT NULL REFERENCES membres(id)",
        "date_remboursement TEXT",
        "montant REAL NOT NULL",
        "moyen_paiement TEXT CHECK(moyen_paiement IN ('chèque', 'virement', 'espèces'))",
        "reference TEXT",
        "commentaire TEXT",
    ),
    # ── Phase 6a — Trésorerie ─────────────────────────────────────────────────
    "comptes_bancaires": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "type_compte TEXT DEFAULT 'bancaire'",
        "solde_initial REAL DEFAULT 0",
        "est_principal INTEGER DEFAULT 0",
        "est_caisse INTEGER DEFAULT 0",
        "iban TEXT",
        "banque TEXT",
        "ordre INTEGER DEFAULT 0",
        "actif INTEGER DEFAULT 1",
        "created_at TEXT DEFAULT (datetime('now'))",
    ),
    "tresorerie_categories": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "type_categorie TEXT NOT NULL DEFAULT 'les_deux' CHECK(type_categorie IN ('recette','depense','les_deux'))",
        "est_systeme INTEGER DEFAULT 0",
        "ordre INTEGER DEFAULT 0",
        "created_at TEXT DEFAULT (datetime('now'))",
    ),
    "tresorerie_operations": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "compte_id INTEGER NOT NULL REFERENCES comptes_bancaires(id)",
        "compte_destination_id INTEGER REFERENCES comptes_bancaires(id)",
        "type_operation TEXT NOT NULL CHECK(type_operation IN ('recette','depense','virement_interne'))",
        "libelle TEXT NOT NULL",
        "montant REAL NOT NULL DEFAULT 0",
        "date_operation TEXT NOT NULL",
        "categorie_id INTEGER REFERENCES tresorerie_categories(id)",
        "mode_paiement TEXT",
        "numero_facture TEXT",
        "evenement_id INTEGER REFERENCES evenements(id)",
        "fournisseur_id INTEGER REFERENCES fournisseurs(id)",
        "statut TEXT NOT NULL DEFAULT 'valide' CHECK(statut IN ('valide','annule','en_attente'))",
        "est_automatique INTEGER DEFAULT 0",
        "source_module TEXT",
        "source_id INTEGER",
        "commentaire TEXT",
        "avance_par_membre_id INTEGER REFERENCES membres(id)",
        "remboursement_statut TEXT DEFAULT 'non_applicable'",
        "remboursement_date TEXT",
        "remboursement_mode TEXT",
        "remboursement_reference TEXT",
        "created_at TEXT DEFAULT (datetime('now'))",
        "updated_at TEXT DEFAULT (datetime('now'))",
    ),
    # ── Phase 7 — Paramètres globaux ─────────────────────────────────────────
    "parametres_globaux": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "cle TEXT NOT NULL UNIQUE",
        "valeur TEXT",
        "updated_at TEXT DEFAULT (datetime('now'))",
    ),
    # ── Phase 9 — Polices PDF ─────────────────────────────────────────────────
    "polices_pdf": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "taille_normale INTEGER DEFAULT 10",
        "taille_titre INTEGER DEFAULT 16",
        "taille_sous_titre INTEGER DEFAULT 13",
        "taille_petit INTEGER DEFAULT 8",
        "est_active INTEGER DEFAULT 0",
        "created_at TEXT DEFAULT (datetime('now'))",
    ),
    # ── Phase 10 — Sauvegardes ───────────────────────────────────────────────
    "sauvegardes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "chemin TEXT NOT NULL",
        "date_creation TEXT NOT NULL",
        "taille_octets INTEGER",
        "type TEXT DEFAULT 'manuelle'",
        "commentaire TEXT",
    ),
    # ── Phase 11/13 — Exercices ──────────────────────────────────────────────
    "exercices": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "date_debut TEXT NOT NULL",
        "date_fin TEXT NOT NULL",
        "statut TEXT NOT NULL DEFAULT 'ouvert' CHECK(statut IN ('ouvert','cloture'))",
        "solde_ouverture REAL DEFAULT 0",
        "commentaire TEXT",
        "created_at TEXT DEFAULT (datetime('now'))",
    ),
    # ── Phase 15/16 — Stock v2 ───────────────────────────────────────────────
    "articles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "reference TEXT",
        "categorie_id INTEGER REFERENCES categories(id)",
        "unite_id INTEGER",
        "fournisseur_id INTEGER REFERENCES fournisseurs(id)",
        "prix_achat REAL DEFAULT 0",
        "prix_vente REAL DEFAULT 0",
        "quantite REAL DEFAULT 0",
        "seuil_alerte REAL DEFAULT 0",
        "description TEXT",
        "commentaire TEXT",
        "actif INTEGER DEFAULT 1",
        "created_at TEXT DEFAULT (datetime('now'))",
        "updated_at TEXT DEFAULT (datetime('now'))",
    ),
    # ── Phase 16 — Cotisations ───────────────────────────────────────────────
    "cotisations": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "adherent_id INTEGER NOT NULL REFERENCES membres(id) ON DELETE CASCADE",
        "exercice_id INTEGER REFERENCES exercices(id) ON DELETE SET NULL",
        "annee INTEGER NOT NULL",
        "montant REAL NOT NULL DEFAULT 0.0",
        "statut TEXT NOT NULL DEFAULT 'offerte' CHECK(statut IN ('offerte','payee','en_attente'))",
        "date_paiement TEXT",
        "mode_paiement TEXT",
        "commentaire TEXT",
        "created_at TEXT NOT NULL DEFAULT (datetime('now'))",
        "updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
    ),
    # ── Phase 17 (migration 0017) — Remboursements enrichis ──────────────────
    # (colonnes ajoutées via ALTER TABLE aux tables existantes)
    # evenement_depenses: avance_par_membre_id, remboursement_statut/date/mode/reference
    # tresorerie_operations: avance_par_membre_id, remboursement_statut/date/mode/reference
    # ── Phase 19 (migration 0019) — Dons ─────────────────────────────────────
    "dons": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "exercice_id INTEGER REFERENCES exercices(id) ON DELETE SET NULL",
        "date_don TEXT NOT NULL",
        "type_donateur TEXT NOT NULL CHECK(type_donateur IN ('particulier','entreprise'))",
        "membre_id INTEGER REFERENCES membres(id) ON DELETE SET NULL",
        "donateur_nom TEXT NOT NULL",
        "donateur_prenom TEXT",
        "donateur_adresse TEXT",
        "donateur_cp TEXT",
        "donateur_ville TEXT",
        "donateur_siret TEXT",
        "nature_don TEXT NOT NULL DEFAULT 'argent' CHECK(nature_don IN ('argent','nature'))",
        "montant REAL",
        "description_don TEXT",
        "valeur_estimee REAL",
        "mode_versement TEXT CHECK(mode_versement IN ('cheque','virement','especes','cb','autre'))",
        "num_recu TEXT UNIQUE",
        "statut_recu TEXT NOT NULL DEFAULT 'en_attente' CHECK(statut_recu IN ('en_attente','emis','annule'))",
        "date_emission_recu TEXT",
        "tresorerie_id INTEGER",
        "commentaire TEXT",
        "created_at TEXT NOT NULL DEFAULT (datetime('now'))",
        "updated_at TEXT NOT NULL DEFAULT (datetime('now'))",
    ),
    # ── Phase 20 (migration 0020) — Tombola lots enrichis ────────────────────
    # (colonnes ajoutées via ALTER TABLE à tombola_lots)
    # tombola_lots: type_provenance, acheteur_membre_id, montant_avance,
    #               remboursement_statut/date/mode/reference, donateur_externe, remarque
}
