"""Définition des noms et colonnes de toutes les tables de l'application.

Ce module ne crée pas les tables — c'est le rôle des migrations.
Il sert de référence unique pour la structure du schéma.
"""

# Chaque entrée est un tuple (nom_table, description)
TABLES = {
    "config": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "exercice TEXT",
        "date_debut TEXT",
        "date_fin TEXT",
        "disponible_banque REAL DEFAULT 0",
        "cloture INTEGER DEFAULT 0",
        "solde_report REAL DEFAULT 0",
    ),
    "membres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "prenom TEXT",
        "email TEXT",
        "telephone TEXT",
        "cotisation REAL DEFAULT 0",
        "statut TEXT DEFAULT 'actif'",
        "date_adhesion TEXT",
        "commentaire TEXT",
    ),
    "events": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "date TEXT",
        "lieu TEXT",
        "description TEXT",
    ),
    "categories": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "parent_id INTEGER REFERENCES categories(id)",
    ),
    "stock": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie_id INTEGER REFERENCES categories(id)",
        "quantite REAL DEFAULT 0",
        "seuil_alerte REAL DEFAULT 0",
        "date_peremption TEXT",
        "commentaire TEXT",
    ),
    "dons_subventions": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT",
        "source TEXT",
        "montant REAL DEFAULT 0",
        "type TEXT",
        "justificatif TEXT",
    ),
    "depenses_regulieres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "categorie TEXT",
        "montant REAL DEFAULT 0",
        "fournisseur TEXT",
        "date_depense TEXT",
        "moyen_paiement TEXT",
        "commentaire TEXT",
    ),
    "depenses_diverses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "categorie TEXT",
        "montant REAL DEFAULT 0",
        "fournisseur TEXT",
        "date_depense TEXT",
        "moyen_paiement TEXT",
        "commentaire TEXT",
    ),
    "depots_retraits_banque": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT",
        "type TEXT",
        "montant REAL DEFAULT 0",
        "reference TEXT",
        "banque TEXT",
        "commentaire TEXT",
    ),
    "fournisseurs": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
    ),
    "historique_clotures": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_cloture TEXT",
        "exercice TEXT",
        "solde_final REAL DEFAULT 0",
    ),
    # --- Buvette ---
    "buvette_articles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie TEXT",
        "prix_vente REAL DEFAULT 0",
        "prix_achat REAL DEFAULT 0",
        "stock_actuel REAL DEFAULT 0",
        "actif INTEGER DEFAULT 1",
    ),
    "buvette_achats": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT",
        "article_id INTEGER REFERENCES buvette_articles(id)",
        "quantite REAL DEFAULT 0",
        "prix_unitaire REAL DEFAULT 0",
        "fournisseur TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaires": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT",
        "event_id INTEGER REFERENCES events(id)",
        "type TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaire_lignes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "inventaire_id INTEGER REFERENCES buvette_inventaires(id)",
        "article_id INTEGER REFERENCES buvette_articles(id)",
        "quantite REAL DEFAULT 0",
    ),
    "buvette_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT",
        "event_id INTEGER REFERENCES events(id)",
        "montant REAL DEFAULT 0",
        "commentaire TEXT",
    ),
    # --- Événements (modules de vente) ---
    "event_modules": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "event_id INTEGER REFERENCES events(id)",
        "nom TEXT NOT NULL",
        "ordre INTEGER DEFAULT 0",
    ),
    "event_module_fields": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER REFERENCES event_modules(id)",
        "nom TEXT NOT NULL",
        "type TEXT DEFAULT 'text'",
        "obligatoire INTEGER DEFAULT 0",
        "ordre INTEGER DEFAULT 0",
    ),
    "event_module_data": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER REFERENCES event_modules(id)",
        "field_id INTEGER REFERENCES event_module_fields(id)",
        "valeur TEXT",
        "created_at TEXT",
    ),
    "event_payments": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "event_id INTEGER REFERENCES events(id)",
        "montant REAL DEFAULT 0",
        "moyen TEXT",
        "date TEXT",
        "commentaire TEXT",
    ),
    "event_caisses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "event_id INTEGER REFERENCES events(id)",
        "nom TEXT NOT NULL",
        "solde_ouverture REAL DEFAULT 0",
        "solde_fermeture REAL DEFAULT 0",
    ),
    "event_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "event_id INTEGER REFERENCES events(id)",
        "categorie TEXT",
        "montant REAL DEFAULT 0",
        "date TEXT",
        "commentaire TEXT",
    ),
    "event_depenses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "event_id INTEGER REFERENCES events(id)",
        "categorie TEXT",
        "montant REAL DEFAULT 0",
        "date TEXT",
        "commentaire TEXT",
    ),
}
