"""Référence descriptive du schéma SQL de l'application."""

TABLES = {
    "config": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom_asso TEXT NOT NULL DEFAULT 'Mon Association'",
        "exercice TEXT",
        "date_debut TEXT",
        "date_fin TEXT",
        "solde_ouverture REAL DEFAULT 0",
        "disponible_banque REAL DEFAULT 0",
        "cloture INTEGER DEFAULT 0",
        "solde_report REAL DEFAULT 0",
    ),
    "membres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "prenom TEXT NOT NULL",
        "email TEXT",
        "telephone TEXT",
        "cotisation TEXT",
        "statut TEXT DEFAULT 'actif'",
        "date_adhesion TEXT",
        "commentaire TEXT",
    ),
    "categories": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL UNIQUE",
        "parent_id INTEGER REFERENCES categories(id)",
    ),
    "evenements": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "date TEXT",
        "lieu TEXT",
        "description TEXT",
    ),
    "stock": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie_id INTEGER REFERENCES categories(id)",
        "quantite INTEGER DEFAULT 0",
        "seuil_alerte INTEGER DEFAULT 0",
        "date_peremption TEXT",
        "lot TEXT",
        "commentaire TEXT",
    ),
    "mouvements_stock": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "stock_id INTEGER NOT NULL REFERENCES stock(id)",
        "date TEXT NOT NULL",
        "type TEXT NOT NULL",
        "quantite INTEGER NOT NULL",
        "prix_unitaire REAL",
        "commentaire TEXT",
    ),
    "dons_subventions": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "source TEXT",
        "montant REAL NOT NULL",
        "type TEXT",
        "justificatif TEXT",
        "commentaire TEXT",
    ),
    "depenses_regulieres": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_depense TEXT NOT NULL",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
    ),
    "depenses_diverses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_depense TEXT NOT NULL",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
    ),
    "depots_retraits_banque": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "type TEXT NOT NULL",
        "montant REAL NOT NULL",
        "reference TEXT",
        "banque TEXT",
        "pointe INTEGER DEFAULT 0",
        "commentaire TEXT",
    ),
    "fournisseurs": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL UNIQUE",
    ),
    "historique_clotures": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_cloture TEXT NOT NULL",
        "exercice TEXT",
        "solde_final REAL",
    ),
    "buvette_articles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "nom TEXT NOT NULL",
        "categorie TEXT",
        "unite TEXT",
        "contenance TEXT",
        "prix_vente REAL DEFAULT 0",
        "prix_achat REAL DEFAULT 0",
        "stock INTEGER DEFAULT 0",
        "commentaire TEXT",
    ),
    "buvette_achats": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "article_id INTEGER NOT NULL REFERENCES buvette_articles(id)",
        "date_achat TEXT NOT NULL",
        "quantite INTEGER NOT NULL",
        "prix_unitaire REAL",
        "fournisseur TEXT",
        "numero_facture TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaires": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date_inventaire TEXT NOT NULL",
        "evenement_id INTEGER REFERENCES evenements(id)",
        "type_inventaire TEXT",
        "commentaire TEXT",
    ),
    "buvette_inventaire_lignes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "inventaire_id INTEGER NOT NULL REFERENCES buvette_inventaires(id)",
        "article_id INTEGER NOT NULL REFERENCES buvette_articles(id)",
        "quantite INTEGER NOT NULL",
        "commentaire TEXT",
    ),
    "buvette_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER REFERENCES evenements(id)",
        "date_recette TEXT NOT NULL",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_modules": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_module TEXT NOT NULL",
    ),
    "evenement_module_champs": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER NOT NULL REFERENCES evenement_modules(id)",
        "nom_champ TEXT NOT NULL",
        "type_champ TEXT NOT NULL",
        "prix_unitaire REAL",
    ),
    "evenement_module_data": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "module_id INTEGER NOT NULL REFERENCES evenement_modules(id)",
        "ligne_index INTEGER NOT NULL",
        "champ_id INTEGER NOT NULL REFERENCES evenement_module_champs(id)",
        "valeur TEXT",
    ),
    "evenement_paiements": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_payeur TEXT",
        "classe TEXT",
        "mode_paiement TEXT",
        "banque TEXT",
        "numero_cheque TEXT",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_caisses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "nom_caisse TEXT NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_recettes": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "source TEXT",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
    "evenement_depenses": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "evenement_id INTEGER NOT NULL REFERENCES evenements(id)",
        "categorie TEXT",
        "montant REAL NOT NULL",
        "fournisseur TEXT",
        "date_depense TEXT",
        "moyen_paiement TEXT",
        "numero_cheque TEXT",
        "numero_facture TEXT",
        "statut_reglement TEXT DEFAULT 'non réglé'",
        "commentaire TEXT",
    ),
    "retrocessions_ecoles": (
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "date TEXT NOT NULL",
        "ecole TEXT NOT NULL",
        "montant REAL NOT NULL",
        "commentaire TEXT",
    ),
}
